services:
  server:
    build: ./server
    container_name: ams_api
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: ams_client
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true 